version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "php"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"